### ISSUE TITLE
New contributions?

### ISSUE THREAD

**Issue by leyuan-sun** [yubaoliu/RDS-SLAM#1]
你好，想问下您的文章和其他dynamic SLAM 相比，创新点在哪里呢，谢谢

**Comment by yubaoliu** [comment]
你好，论文正在审稿，论文中有跟其它slam的详细对比，请再稍等一段时间 。谢谢

**Comment by leyuan-sun** [comment]
你好，谢谢您的回复，我看了您提供的demo, 除了数据上（ATE,RPE）以外，还有什么别的创新点么，能大概讲一下么，不需要具体的实现细节。

**Comment by yubaoliu** [comment]
主要贡献是实时性，最快速度可与ORB SLAM3相同，性能与其它方案差不多。实现方法还是看论文吧，有点复杂，再等一个月左右吧。

**Comment by leyuan-sun** [comment]
谢谢您的回复，mask rcnn 结合您的方法 系统的fps能到多少呢，还有能问一下您投的是什么会议么？

**Comment by yubaoliu** [comment]
大约30HZ吧，22-33ms每帧，我也用了Mask R-CNN，视频demo有。投的期刊。
