### ISSUE TITLE
Segnet_pascal.caffemodel could not download.....

### ISSUE THREAD

**Issue by zhuhu00** [yubaoliu/RDS-SLAM#10]
The official website contains `Segnet_pascal.caffemodel` is down, I could not download from the official site, Do you have this model file? Could you send me a copy, my email address is zhuh2020@mail.sustech.edu.cn.

**Comment by TonyPJ-deop** [comment]
I also have this question,Could you please share your model to me,my email address is 220192216092@ncepu.edu.cn.

**Comment by JiuDin** [comment]
Me too, Could you please share your model to me,my email address is  3195661858@qq.com

**Comment by JXFOnestep** [comment]
Me too, Could you please share your model to me,my email address is 1241138130@qq.com  ，Thanks a lot

**Comment by zhouyong1234** [comment]
Me too, Could you please share your model to me,my email address is m15988816746@163.com

**Comment by Hakunamatatalj** [comment]
Is there any brother who can send me a copy? thanks 1615564727@qq.com

**Comment by wafaer** [comment]
Me too, Could you please share your model to me,my email address is 320553214@qq.com

**Comment by JXFOnestep** [comment]
https://pan.baidu.com/s/1gkI7nAvijF5Fjj0DTR0rEg%E3%80%90%E5%AF%86%E7%A0%81%EF%BC%9Afpa3%E3%80%91&nbsp;------------------
From: hermione ***@***.***&gt;
Date: Sun,Jul 10,2022 5:00 PM
To: yubaoliu/RDS-SLAM ***@***.***&gt;
Cc: JXFOnestep ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [yubaoliu/RDS-SLAM] Segnet_pascal.caffemodel could notdownload..... (Issue #10)





 
Me too, Could you please share your model to me,my email address is ***@***.***

**Comment by wafaer** [comment]
> https://pan.baidu.com/s/1gkI7nAvijF5Fjj0DTR0rEg%E3%80%90%E5%AF%86%E7%A0%81%EF%BC%9Afpa3%E3%80%91&nbsp;------------------ From: hermione ***@***.***&gt; Date: Sun,Jul 10,2022 5:00 PM To: yubaoliu/RDS-SLAM ***@***.***&gt; Cc: JXFOnestep ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [yubaoliu/RDS-SLAM] Segnet_pascal.caffemodel could notdownload..... (Issue #10) Me too, Could you please share your model to me,my email address is ***@***.*** — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
非常感谢你提供资源，但是输入提取码fpa3提示提取码错误，请问提取码能提供一下吗，感谢

**Comment by shubhamshankar28** [comment]
Could you please share the Segnet_pascal.caffemodel with me, the official website is down. My email address is [shubham.shankar@iitg.ac.in](shubham.shankar@iitg.ac.in).

**Comment by Baymax958** [comment]
Me too, Could you please share your model to me,my email address is 1187915640@qq.com

**Comment by zarathacia** [comment]
Hello can you plz share a copy of the segnet_pascal.caffemodel my email address is ayabenslimen.aya7@gmail.com

**Comment by AbsoluteResonance** [comment]
Me too, Could you please share your model to me, thanks, my email address is xfy464840129@gmail.com

**Comment by Hakunamatatalj** [comment]
链接：https://pan.baidu.com/s/1iHdgEpq_TPM91rTAGgZhJw 
提取码：ghxx 
--来自百度网盘超级会员V3的分享
