### ISSUE TITLE
When will the code be open source?

### ISSUE THREAD

**Issue by hanpengpeng123** [yubaoliu/RDS-SLAM#3]
Can you send the code to my mailbox 1421384659@qq.com

**Comment by hanpengpeng123** [comment]
thank you very much

**Comment by hanpengpeng123** [comment]
Thank you very much

**Comment by yubaoliu** [comment]
Sorry, please wait for some more time. Currently, the license information has not added and the source code is not ready for publication. If you have any questions about the paper, please feel free to ask.
