### ISSUE TITLE
经过我的调试与修改，已经能运行个百分之80了，还是有一点问题，希望可以请教

### ISSUE THREAD

**Issue by minghongss** [yubaoliu/RDS-SLAM#8]
大佬你好，感谢你的开源，因为我看你也是中国人，就不用英语进行提问
![Screenshot from 2021-11-11 17-15-13](https://user-images.githubusercontent.com/76800494/141271401-de14dcae-db57-4f09-b5ef-45dce6b3ef71.png)
。
我认为我已经基本跑起来了，但是貌似在maskrcnn这里出现了问题。我的配置是tensorflow-gpu1.9.0，cuda9.0，cudnn7.3.1,我的这个环境配置运行过dynaslam，是没有问题的。我认为问题貌似出现在了maskrcnn的这边，我网上查了相关的资料，网上说是添加以下语句：
import tensorflow as tf
#=======
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
session = tf.Session(config=config)
#=======
这个语句是控制显存，不让显存溢出的，我在几个可能的py文件里都添加了上面语句（.../catkin_ws/src/MaskRCNN_ROS/include/MaskRCNN/samples/coco/coco.py     .../catkin_ws/src/MaskRCNN_ROS/script/action_server.py   .../catkin_ws/src/MaskRCNN_ROS/include/MaskRCNN/samples/demo.py）
但是结果依然没有变化，是因为cuda和tensorflow的版本问题吗？还是需要在别的文件添加上面的语句？
十分希望大佬百忙之中回复，非常感谢!

**Comment by minghongss** [comment]
我认为不应该是显存溢出，因为我通过指令，指定只使用了50%的显存，依旧出现这种情况。

**Comment by zlthaha** [comment]
> 

您好，我也在尝试运行此程序，可以加个联系方式吗？我有些调试方面的问题想跟您请教一下

**Comment by zlthaha** [comment]
> 大佬你好，感谢你的开源，因为我看你也是中国人，就不用英语进行提问 ![Screenshot from 2021-11-11 17-15-13](https://user-images.githubusercontent.com/76800494/141271401-de14dcae-db57-4f09-b5ef-45dce6b3ef71.png) 。 我认为我已经基本跑起来了，但是貌似在maskrcnn这里出现了问题。我的配置是tensorflow-gpu1.9.0，cuda9.0，cudnn7.3.1,我的这个环境配置运行过dynaslam，是没有问题的。我认为问题貌似出现在了maskrcnn的这边，我网上查了相关的资料，网上说是添加以下语句： import tensorflow as tf #======= config = tf.ConfigProto() config.gpu_options.allow_growth = True session = tf.Session(config=config) #======= 这个语句是控制显存，不让显存溢出的，我在几个可能的py文件里都添加了上面语句（.../catkin_ws/src/MaskRCNN_ROS/include/MaskRCNN/samples/coco/coco.py .../catkin_ws/src/MaskRCNN_ROS/script/action_server.py .../catkin_ws/src/MaskRCNN_ROS/include/MaskRCNN/samples/demo.py） 但是结果依然没有变化，是因为cuda和tensorflow的版本问题吗？还是需要在别的文件添加上面的语句？ 十分希望大佬百忙之中回复，非常感谢!

您好，我也在尝试运行此程序，可以加个联系方式吗？我有些调试方面的问题想跟您请教一下

**Comment by zhouyong1234** [comment]
你好，请问我把launch文件启动后，界面卡住不动是什么原因呢
![2022-05-11 13-49-01屏幕截图](https://user-images.githubusercontent.com/46642375/167777939-9ef64dcd-2536-4d74-ad7f-600f523b31db.png)

**Comment by minghongss** [comment]
> 你好，请问我把launch文件启动后，界面卡住不动是什么原因呢 ![2022-05-11 13-49-01屏幕截图](https://user-images.githubusercontent.com/46642375/167777939-9ef64dcd-2536-4d74-ad7f-600f523b31db.png)

不好意思哈，我是用的maskrcnn，我也不清楚为啥，你这个看起来貌似没都挺正常，感觉像是segnet那边卡住了的。我也只跑了maskrcnn，而且这个工程之前由于一些原因，被误删了

**Comment by zhouyong1234** [comment]
好的，我试试

**Comment by hongli01** [comment]
> 你好，请问我把launch文件启动后，界面卡住不动是什么原因呢 ![2022-05-11 13-49-01屏幕截图](https://user-images.githubusercontent.com/46642375/167777939-9ef64dcd-2536-4d74-ad7f-600f523b31db.png)

大佬，可以留个联系方式吗，请教一下
