### ISSUE TITLE
成功运行，但是存有一些疑问，望大佬解答。感谢

### ISSUE THREAD

**Issue by minghongss** [yubaoliu/RDS-SLAM#9]
大佬您好，感谢你的开源！都是中国人，这里我就用中文进行提问了
![Screenshot from 2021-11-11 18-37-49](https://user-images.githubusercontent.com/76800494/141284069-46975e72-dec5-420c-8ff9-156c3af37816.png)
。
computeActiveErrors(): found NaN in error for edge 0x7f94f49c4d00这是否是正常，是什么原因导致？有没有方法去除？

**Comment by minghongss** [comment]
我通过取消--march=native的编译选项，解决了该问题。我已经看了您的源码，我有个疑问mptSemanticBA = new std::thread(&Semantic::SemanticBAThread, this);
为什么要注释掉这条语句呢？

**Comment by yubaoliu** [comment]
SemanticBAThread 这个线程我没有在这个版本里进行调试。在后续的工作RDMO-SLAM中我把这个线程去掉了。您需要的话可以加上。

**Comment by yubaoliu** [comment]
目前这个开源版本与论文是不太一样的，只保留了核心思想供参考。我正准备改写下一个版本，可能要等比较长的时间。

**Comment by minghongss** [comment]
感谢您的回答，我还有两个问题想要询问您。1.我发现，您是使用了RGBD的模式，但是我注意到深度图片貌似只在构建frame类时使用到，也就是只在恢复三维点时用到了深度信息，在后续对于动态物体的检测和移动概率的更新并没有用到深度图片的信息。我在想为什么选用了RGBD相机呢？双目不也是能够较好的恢复深度吗？是因为动态物体也会影响双目的深度恢复吗？2.orbslam3最大一个新地方是紧耦合了IMU，我认为IMU是不会受到动态物体影响，是否有可能利用imu信息呢？如果没有使用IMU信息，那我觉得选择orbslam2和orbslam3作为框架的意义并不大，虽然多地图集可能在一定意义上能够处理跟踪丢失的情况。

**Comment by yubaoliu** [comment]
1.我发现，您是使用了RGBD的模式，但是我注意到深度图片貌似只在构建frame类时使用到，也就是只在恢复三维点时用到了深度信息，在后续对于动态物体的检测和移动概率的更新并没有用到深度图片的信息。我在想为什么选用了RGBD相机呢？
>论文思想与是否RGBD模式无关，单目，Stereo都是可以的。使用RGBD模式：a) 方便与其它论文工作进行对比， b)尽量排除其它因素的影响
双目不也是能够较好的恢复深度吗？
>双目也可以啊，有深度/预测的深度，即可。用CNN来作深度估计也可以的。
是因为动态物体也会影响双目的深度恢复吗？
> 双目估计影响不大吧

2.orbslam3最大一个新地方是紧耦合了IMU，我认为IMU是不会受到动态物体影响，是否有可能利用imu信息呢？
>可以用IMU，此处重点不是谈IMU的事情。如果加IMU的话，没有合适的数据集单独对IMU的作用进行验证。
> 论文重点是如何让CNN与视觉SLAM进行结合，但不影响视觉SLAM的速度。动态SLAM只是其中的一个应用，还可以构建语义地图，环境感知。此论文的用意点不仅仅是动态SLAM问题。

如果没有使用IMU信息，那我觉得选择orbslam2和orbslam3作为框架的意义并不大，虽然多地图集可能在一定意义上能够处理跟踪丢失的情况。
>是的，区别不大

**Comment by yubaoliu** [comment]
有个使用IMU的论文，Visual odometry algorithm using an RGB-D sensor and IMU in a highly dynamic environment，效果比较一般。需要自己制作数据集进行验证。

**Comment by minghongss** [comment]
十分感谢您的解答，我下去会去思考的。我很期待您的下一个版本。希望能在不久见到您的新paper。

**Comment by minghongss** [comment]
大佬，您好，我看了您的RDMO-SLAM这篇论文，我对其中利用稠密光流预测label这部分很感兴趣，我已经了解了您的预测原理，我想进一步通过源码进行学习，看一下实际效果。不知道您的这个RDMO-SLAM是否会开源？

**Comment by yubaoliu** [comment]
目前没有开源RDMO-SLAM的源码，论文里有一些模块的参考代码链接。
